package com.buschmais.testbeans.testng.common;

enum Event {

	BEGINSUITE, BEGINCLASS, BEFORESUITE, BEFORETEST, BEFORECLASS, BEFOREMETHOD, METHOD, AFTERMETHOD, AFTERCLASS, AFTERTEST, AFTERSUITE, ENDCLASS, ENDSUITE;

}
